### PR TITLE
white-devil00201

### PR DESCRIPTION
**Pull request by Nisarg-Mehta28**
Hello there,

In this project I have taken the reference from the website and you-tube videos to successfully complete my project.

Thank You

### CODE REVIEW

**Comment by jayskhatri** [comment]
Hey @white-devil0201  👋,

I just want to be sure. Is the whole code of animation made by yourself? or have you taken the same code from the tutorials which you are talking about?🤔

**Comment by Nisarg-Mehta28** [comment]
Hello there

Thank you for reaching me I am glade you have seen my code. I have seen
many tutorial and then I made my own design then I put my ideas in that and
I made my own code and animation. I didn't take the code directly from that
tutorial, this code is made by me from scratch. So I hope your dought is
clear if there is anything else you like to know about you can ping me mail.

Thank you 😊

**Comment by jayskhatri** [comment]
> 
> Hello there Thank you for reaching me I am glade you have seen my code. I have seen many tutorial and then I made my own design then I put my ideas in that and I made my own code and animation. I didn't take the code directly from that tutorial, this code is made by me from scratch. So I hope your dought is clear if there is anything else you like to know about you can ping me mail. Thank you 😊

Thank you for clearing out👍

**Review by jayskhatri — APPROVED** [review]
Good to go👍

Congratulations on making the submission ✨

**Comment by Nisarg-Mehta28** [comment]
I want to ask one thing that when you open my project at that time did you
get background sound in my site or not because i have put the background
sound in my site so can you please tell me because in my chrome browser
background sound is not played but in firefox background sounds plays
perfectly so can you please tell me

**Comment by chirayu-joshi** [comment]
Chrome doesn't autoplay audio or video until there is some user activity. I also faced the same issue,  and there is no solution to it, except using different browser.

**Comment by Nisarg-Mehta28** [comment]
ya I know so can you please open my file in another browser when the judges
are going to see the implementation of all the participants because sound
plays an important role in my project, that's why I am telling you if you
don't mind.

**Pull request merged**
